### ISSUE TITLE
Lab Oven Reactor - Bad Fluid Input System Intereaction

### ISSUE THREAD

**Issue by iopredman** [GlobbyPotato/Rockhounding_Chemistry#126]
Expected behavior: Fluid Input System, which is filled with water, allows for the creation of acidic water by reacting with chloride bearing compound in the Lab Oven Reactor.

Observed behavior: Multi-Block does not produce acidic water and seems to not be accepting the water from the fluid input system. Mining the fluid input system does not produce a block drop and throws this server error:

[20:04:49] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
	at com.globbypotato.rockhounding_chemistry.machines.MachinesA.addLabOvenIntankNbt(MachinesA.java:608) ~[MachinesA.class:?]
	at com.globbypotato.rockhounding_chemistry.machines.MachinesA.func_180657_a(MachinesA.java:521) ~[MachinesA.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:327) ~[or.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:244) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:704) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

Minecraft Version: 1.12.2
Forge Version: 14.23.5.2847
Mod Version: 3.51
Pack: Custom Enigmatica 2 (No RH-related crafttweaking has been done)

**Comment by iopredman** [comment]
Just realized that (both) means I need both types of fuel. Lab Oven Reactor is working now but Fluid Input System is still not dropping correctly.

**Comment by GlobbyPotato** [comment]
Thanks for reporting, fixed it. Sorry for the issue.

**Comment by iopredman** [comment]
Cheers!
