### ISSUE TITLE
Slot 2 not in valid range - Ticking Block entity

### ISSUE THREAD

**Issue by AnodeCathode** [GlobbyPotato/Rockhounding_Chemistry#136]
With Lab Oven Controller

RH Core: rockhounding_core-1.12.2-3.24
RH Chem: rockhounding_chemistry-1.12.2-3.53

Description: Ticking block entity

java.lang.RuntimeException: Slot 2 not in valid range - [0,2)
    at net.minecraftforge.items.ItemStackHandler.validateSlotIndex(ItemStackHandler.java:214)
    at net.minecraftforge.items.ItemStackHandler.getStackInSlot(ItemStackHandler.java:73)
    at com.globbypotato.rockhounding_core.machines.tileentity.MachineStackHandler.damageSlot(MachineStackHandler.java:151)
    at com.globbypotato.rockhounding_core.machines.tileentity.MachineStackHandler.damageUnbreakingSlot(MachineStackHandler.java:196)
    at com.globbypotato.rockhounding_chemistry.machines.tile.TELabOvenController.process(TELabOvenController.java:496)
    at com.globbypotato.rockhounding_chemistry.machines.tile.TELabOvenController.TickCentral_TrueITickableUpdate(TELabOvenController.java:368)
    at com.github.terminatornl.tickcentral.api.TickHub.trueUpdate(TickHub.java:48)
    at com.github.terminatornl.laggoggles.Main.redirectUpdate(Main.java:91)
    at com.globbypotato.rockhounding_chemistry.machines.tile.TELabOvenController.update(TELabOvenController.java)
    at net.minecraft.world.World.redirect$zbg000$tileEntityUpdate(World.java:4137)
    at net.minecraft.world.World.updateEntities(World.java:1838)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)

**Comment by GlobbyPotato** [comment]
oops! Bad coder is bad.
It happens if the oven recipe uses a catalyst. The machine is searching for the catalyst in the solute slot. It may happen with the Precipitation Chamber a well. Fixing it. Sorry.
