### ISSUE TITLE
Ore Dictionary

### ISSUE THREAD

**Issue by bookerthegeek** [GlobbyPotato/Rockhounding_Chemistry#25]
```
[22:00:04] [main/WARN] [FML]: ****************************************
[22:00:04] [main/WARN] [FML]: * Invalid registration attempt for an Ore Dictionary item with name oreUninspected has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[22:00:04] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:642)
[22:00:04] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:628)
[22:00:04] [main/WARN] [FML]: *  at com.globbypotato.rockhounding_chemistry.handlers.ModDictionary$RegistrationHandler.registerOreDictEntries(ModDictionary.java:30)
[22:00:04] [main/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_249_RegistrationHandler_registerOreDictEntries_Register.invoke(.dynamic)
[22:00:04] [main/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[22:00:04] [main/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)...
[22:00:04] [main/WARN] [FML]: ****************************************
[22:00:04] [main/WARN] [FML]: ****************************************
[22:00:04] [main/WARN] [FML]: * Invalid registration attempt for an Ore Dictionary item with name blockRawsalt has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[22:00:04] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:642)
[22:00:04] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:628)
[22:00:04] [main/WARN] [FML]: *  at com.globbypotato.rockhounding_chemistry.handlers.ModDictionary$RegistrationHandler.registerOreDictEntries(ModDictionary.java:33)
[22:00:04] [main/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_249_RegistrationHandler_registerOreDictEntries_Register.invoke(.dynamic)
[22:00:04] [main/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[22:00:04] [main/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)...
[22:00:04] [main/WARN] [FML]: ****************************************
[22:00:04] [main/WARN] [FML]: ****************************************
[22:00:04] [main/WARN] [FML]: * Invalid registration attempt for an Ore Dictionary item with name blockCharcoal has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[22:00:04] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:642)
[22:00:04] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:628)
[22:00:04] [main/WARN] [FML]: *  at com.globbypotato.rockhounding_chemistry.handlers.ModDictionary$RegistrationHandler.registerOreDictEntries(ModDictionary.java:34)
[22:00:04] [main/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_249_RegistrationHandler_registerOreDictEntries_Register.invoke(.dynamic)
[22:00:04] [main/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[22:00:04] [main/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)...
[22:00:04] [main/WARN] [FML]: ****************************************
```
### Versions ###
- forge-1.12.2-14.23.2.2624-universal.jar
- rockhounding_chemistry-1.12.2-3.04
- rockhounding_core-1.12.2-3.06
- rockhounding_oretiers-1.12.2-3.04

**Comment by GlobbyPotato** [comment]
Hi, I checked the logs but I didn't find these errors. Those blocks seem correctly oredicted.
